# Generated by Django 5.1.3 on 2024-12-04 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('industry_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('role_category', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee')], max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
