# Generated by Django 5.1.7 on 2025-03-26 05:33

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255, verbose_name='Certification Name')),
                ('issued_date', models.DateField(verbose_name='Certification Issued Date')),
                ('certificate_file', models.FileField(help_text='Upload PDF, JPG, or PNG', upload_to=main.models.certification_file_path, verbose_name='Certification Document')),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing Organization')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Certification Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Certification',
                'verbose_name_plural': 'Employee Certifications',
                'ordering': ['-issued_date'],
            },
        ),
    ]
