# Generated by Django 5.1.3 on 2024-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_experience_projects_userprofile_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
