# Generated by Django 5.1.7 on 2025-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
