# Generated by Django 5.1.3 on 2024-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
