# Generated by Django 5.1.3 on 2024-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
