# Generated by Django 5.1.3 on 2024-12-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_applied_at_jobapplication_applied_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
    ]
