# Generated by Django 5.1.3 on 2024-12-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user_profile',
        ),
    ]
