# Generated by Django 5.1.3 on 2024-12-11 12:54

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_jobapplication_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='user_profile',
            field=models.ForeignKey(default=main.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
    ]
